:toc: macro
:toc-title: Summary
:toclevels: 3
:numbered:

ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

:back_to_top_target: top-target
:back_to_top_label: ⬆ Back to top
:back_to_top: <<{back_to_top_target},{back_to_top_label}>>

:main_title: Chrome Extension & Angular (Starter Kit)
:git_project: chrome-extension-angular-starter-kit
:git_username: jprivet-dev
:git_url: https://github.com/{git_username}/{git_project}
:git_clone_ssh: git@github.com:{git_username}/{git_project}.git

[#{back_to_top_target}]
= {main_title}

toc::[]

== Presentation

Base of a Chrome extension made with Angular.

{back_to_top}

== Installation

[subs=attributes+]
```
$ git clone {git_clone_ssh}
```

{back_to_top}

== Step by step creation

=== Generate a new application

```
$ ng new app --directory . --prefix app --routing true --style scss --skip-git true --defaults --strict
```

=== Create the popup module

```
$ ng generate module popup --routing
```

=== Create the target guard

```
$ ng generate guard target
```

=== Create the options module

```
$ ng generate module options --routing
```

=== Create background.js

```
npm i -D @angular-builders/custom-webpack
```

=== Create content_scripts.js
=== Install a color picker

```
$ npm i ngx-color-picker
```

{back_to_top}

== Troubleshooting

=== A violation of the Content Security Policy

As soon as you modify the `style.css` file, for example:

```css
body {
  margin: 0;
}
```

You will get this error at runtime:

```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

Because of the following line in the generated HTML:

```
  <style>body{margin:0}</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css"></noscript></head>
```

It is because of inline scripting. Angular generates code by default that violates the https://developer.chrome.com/docs/apps/contentSecurityPolicy/[Content Security Policy]:

> You can't use inline scripting in your Chrome App pages. The restriction bans both <script> blocks and event handlers (<button onclick="...">).

I used this solution https://github.com/angular/angular-cli/issues/20864#issuecomment-844823912.

Instead of

```json
"optimization": true
```

put

```json
"optimization": {
  "scripts": true,
  "styles": {
    "minify": true,
    "inlineCritical": false
  },
  "fonts": true
},
```

{back_to_top}

== Resources & Inspiration

* https://www.justjeb.com/post/chrome-extension-with-angular-from-zero-to-a-little-hero
* https://medium.com/@BiigDigital/angular-et-la-configuration-webpack-1f9398313e43
* https://stackoverflow.com/questions/44208107/building-chrome-extension-popup-options-and-background-using-angular-cli
* https://stackoverflow.com/questions/67980170/chrome-extension-background-script-into-multiple-scripts-manifest-v3
* https://developer.chrome.com/docs/extensions/mv3/getstarted/
* https://developer.chrome.com/docs/extensions/mv3/content_scripts/

{back_to_top}

== License

{main_title} is released under the {git_url}/blob/main/LICENSE[*MIT License*]

---

{back_to_top}
